name: Static Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and push to static repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "tsil-ukr/archive-static"
          path: ".будування"
      - uses: actions/checkout@v4
        with:
          repository: "tsil-ukr/website"
          path: ".вебсайт"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm i -g xdocs
          npm i -g sass
          bash згенерувати.sh
          cd .будування
          git config --local user.name "kohutd"
          git config --local user.email "davyd.kohut@gmail.com"
          git commit -a -m "!"
      - uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: ".будування"
          repository: "tsil-ukr/archive-static"
          ssh: true
          github_token: ${{ secrets.SSH_DEPLOY_KEY }}